[package]
name = "afl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sort_comp = { path = ".." }
afl = "0.12"

[profile.release]
debug = 1
