[package]
name = "sort_comp"
version = "0.1.0"
edition = "2021"
# type = "lib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
once_cell = "1.15"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false

[features]
default = []

# Enable support for libcxx.
# You must provide a prebuild static libcxx see: https://libcxx.llvm.org/BuildingLibcxx.html
libcxx = []

# Enable wpwoodjr sort.
# No additional requirements, but disabled by default to keep things lean.
wpwoodjr = []
