[package]
name = "sort_comp"
version = "0.1.0"
edition = "2021"
# type = "lib"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
once_cell = "1.15"
radsort = { version = "0.1", optional = true }
dmsort = { version = "1.0", optional = true }

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[build-dependencies]
cc = "1.0"

[[bench]]
name = "bench"
harness = false

[features]
default = []

# Enable support for C++ std::sort and std::sort_stable.
cpp_std = []

# Enable support for libcxx.
# You must provide a prebuild static libcxx see: https://libcxx.llvm.org/BuildingLibcxx.html
# Set the enviroment variable LIBCXX_CUSTOM_BUILD_DIR=<...>
# This overrides the cpp_std library used.
# Requires "cpp_std" feature.
libcxx = []

# Enable support for cpp_pdqsort.
# Uses system C++ standard lib.
cpp_pdqsort = []

# Enable wpwoodjr sort.
# No additional requirements, but disabled by default to keep things lean.
wpwoodjr = []

# Enable radsort. Radix sort used by bevy.
# No additional requirements, but disabled by default to keep things lean.
bevy_radsort = ["radsort"]

# Enable drop-merge sort developed by Emil Ernerfeldt (emilk)
# No additional requirements, but disabled by default to keep things lean.
emilk_dmsort = ["dmsort"]
